# cc-connect 配置文件
language = "zh"
data_dir = "/Users/haorui/.cc-connect"

[log]
level = "debug"

[[projects]]
name = "AI"

[projects.agent]
type = "claudecode"

[projects.agent.options]
work_dir = "/Users/haorui/workspace"
mode = "default"
provider = "wecode"

[[projects.agent.providers]]
name = "wecode"
api_key = "sk-wecode-proxy-claude-code-sk"
base_url = "http://127.0.0.1:3456"

# 微博平台配置
[[projects.platforms]]
type = "weibo"

[projects.platforms.options]
app_id = "5288417333608449"
app_secret = "dcccd6cfca5d43bdfa81fca8fea490458358995eeed717b44a2379e38ae0a509"
token_url = "http://open-im.api.weibo.com/open/auth/ws_token"
ws_url = "ws://open-im.api.weibo.com/ws/stream"
allow_from = "*"
account_id = "default"
